apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: nginx
spec:
  provider: aws
  secretObjects:
    - secretName: ssm-params
      type: Opaque
      labels:
        app: nginx
      data:
        - objectName: documentdb_host
          key: documentdb_host_param
  parameters:
    objects: |
      - objectName: "DOCUMENTDB_HOST"
        objectType: ssmparameter
        objectAlias: documentdb_host