---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: "karpenter-eks-demo-cluster-20240625093325074600000002"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-demo-cluster"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-demo-cluster"